server:
  port: 8015

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yun_live?serverTimezone=UTC&allowMultiQueries=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=True&allowMultiQueries=true
    username: xxxx
    password: xxxx