spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /api

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lance.yunlive.mapper
  configuration:
    map-underscore-to-camel-case: true